"""update

Revision ID: 8d75d9402312
Revises: c933d4b5b8c4
Create Date: 2025-06-24 16:29:08.951230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d75d9402312'
down_revision = 'c933d4b5b8c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('apartment_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('apartment_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
