"""apts

Revision ID: c933d4b5b8c4
Revises: 
Create Date: 2025-06-11 14:56:58.704924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c933d4b5b8c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apartment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apartment_name'), ['name'], unique=False)

    op.create_table('preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('preference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_preference_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('f_name', sa.String(length=45), nullable=False),
    sa.Column('l_name', sa.String(length=45), nullable=False),
    sa.Column('bio', sa.String(length=180), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_bio'), ['bio'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_f_name'), ['f_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_l_name'), ['l_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('match',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user1', sa.Integer(), nullable=False),
    sa.Column('user2', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user1'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user2'], ['user.id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_user1'), ['user1'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_user2'), ['user2'], unique=False)

    op.create_table('message',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('reciever_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=180), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reciever_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_message'), ['message'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_reciever_id'), ['reciever_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_sender_id'), ['sender_id'], unique=False)

    op.create_table('rating',
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('reciever_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=180), nullable=False),
    sa.ForeignKeyConstraint(['reciever_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('rating_id')
    )
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rating_message'), ['message'], unique=False)
        batch_op.create_index(batch_op.f('ix_rating_reciever_id'), ['reciever_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rating_sender_id'), ['sender_id'], unique=False)

    op.create_table('user__preference',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preference_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['preference_id'], ['preference.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'preference_id')
    )
    with op.batch_alter_table('user__preference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user__preference_preference_id'), ['preference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user__preference_rank'), ['rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_user__preference_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user__preference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user__preference_user_id'))
        batch_op.drop_index(batch_op.f('ix_user__preference_rank'))
        batch_op.drop_index(batch_op.f('ix_user__preference_preference_id'))

    op.drop_table('user__preference')
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_sender_id'))
        batch_op.drop_index(batch_op.f('ix_rating_reciever_id'))
        batch_op.drop_index(batch_op.f('ix_rating_message'))

    op.drop_table('rating')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_sender_id'))
        batch_op.drop_index(batch_op.f('ix_message_reciever_id'))
        batch_op.drop_index(batch_op.f('ix_message_message'))

    op.drop_table('message')
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_user2'))
        batch_op.drop_index(batch_op.f('ix_match_user1'))

    op.drop_table('match')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_l_name'))
        batch_op.drop_index(batch_op.f('ix_user_f_name'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_bio'))

    op.drop_table('user')
    with op.batch_alter_table('preference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preference_name'))

    op.drop_table('preference')
    with op.batch_alter_table('apartment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apartment_name'))

    op.drop_table('apartment')
    # ### end Alembic commands ###
